### ISSUE TITLE
Some Games works incorrect

### ISSUE THREAD

**Issue by setsuna362** [MiSTer-devel/NES_MiSTer#134]
GoodNES v3.23b Roms
Mapper#32 Major League (J) [!].nes (d8dfd3d1) Outfield area incorrect
Mapper#33 Power Blazer (J) [!].nes (2b17a194) start game, background tank Graphic broken
Mapper#33 Takeshi no Sengoku Fuuunji (J) [!].nes (5c80a4a2) Graphic broken
Mapper#68 Maharaja (J) [!].nes (b9083fde) Graphic broken
Mapper#80 Fudou Myouou Den (J) [!].nes (6e1f3c62) Graphic broken

**Comment by greyrogue** [comment]
Mapper 33 is now fixed for Power Blazer and Takeshi no Sengoku Fuuunji in PR #136.
Major League did have an issue which is now fixed in the same PR, but it also requires a NES 2.0 header with submapper 1: 4E 45 53 1A 08 10 00 28 10 00 00 00 00 00 00 00
Fudou Myouou Den is mapper 207, not mapper 80: 4E 45 53 1A 10 10 F0 C0 00 00 00 00 00 00 00 00
(See note here: https://wiki.nesdev.com/w/index.php/INES_Mapper_080)
Maharaja was fixed a couple days before this report: #132, but wasn't released until today.  Are there additional issues?

**Comment by MP2E** [comment]
Seems this can be closed, I tested these games and found no issues

**Comment by Left-Empty** [comment]
I have the same graphical glitch issue in Fudou Myouou Den, with the same CRC as Setsuna362.
Demon Sword, the US version, doesn't exhibit this problem.

**Comment by paulb-nl** [comment]
> I have the same graphical glitch issue in Fudou Myouou Den, with the same CRC as Setsuna362.

This is addressed in greyrogue's comment. The rom is set to the wrong mapper.

**Comment by Left-Empty** [comment]
Ah sorry, I was thinking he was correcting the original poster, not that it was the root of the problem!

**Comment by Tuxosaurus** [comment]
Since this is open and the title suits my needs, I'm posting here but please correct me if you need a new issue for this.

I tried with several roms (including those in GoodNES v3.23b) and both "Family Circuit" and "Family Circuit '91" have tiles all over the place:
![20200419_150951-Family Circuit (J)  o1](https://user-images.githubusercontent.com/373381/79691756-974bfe80-8261-11ea-9e78-f29a77faf8e9.png)
![20200419_151155-Family Circuit '91 (J)  o3](https://user-images.githubusercontent.com/373381/79691757-97e49500-8261-11ea-9e22-33d3cfa5c176.png)

**Comment by Tuxosaurus** [comment]
I was sent NES 2.0 roms for the Family Circuit games, that works fine.
I guess we can close the issue then.
