### ISSUE TITLE
Alpha Mission garbled graphics within first 20 seconds of the gameplay for a couple of seconds

### ISSUE THREAD

**Issue by suverman** [MiSTer-devel/NES_MiSTer#152]
Alpha Mission garbled graphics within first 20 seconds of the gameplay for a couple of seconds - I tried it twice, it happened both times. I couldnt find anything online regarding this. Please close if you feel this is normal behaviour. I havent tested this on real hardware.

**Comment by SegaSnatcher** [comment]
Can you please post a screenshot or video?

**Comment by suverman** [comment]
![Alpha Base](https://user-images.githubusercontent.com/42350878/70363672-718b1200-18dd-11ea-9021-da4c6a790aa2.jpg)
Sure there is the screenshot if anyone else is looking for it. I am running the latest official release as well. I shall close the issue if you want now or as soon as the newer build is out - I can check and close. Thanks.

**Comment by MP2E** [comment]
Been a bit distracted by the GBA core recently, but I just checked this out and I can confirm this is an issue. Thanks for reporting! I'll look into it

**Comment by MP2E** [comment]
Figured it out. This game needs an NES 2.0 header, and then needs to be set to Submapper 1. The reason the game glitches out without this is that it runs on a CNROM board that has no bus conflicts. Bus conflicts are emulated by default in mapper 3, so that causes this game to break. Submapper 1 will tell MiSTer to not emulate bus conflicts for this board

**Comment by suverman** [comment]
Thanks MP2E's advise works, the ROM needs to be updated with NES 2.0 submapper 1 and it solves the problem.
