### ISSUE TITLE
Suggestion for a better savestate bind

### ISSUE THREAD

**Issue by Toryalai1** [MiSTer-devel/NES_MiSTer#259]
Hello,
I have recently discovered the savestate functionality in a couple of cores, NES included which FPGAzumSpass has implemented. Would it be possible to instead make it so that you can press Savestate + up or down to save and load state? Right now you have to press savestate+start+up or down to save or load which requires me to "claw" my controller. I usually play with my M30 controller which happens to have more buttons than a regular NES pad. My suggestion is to have an option so that the user can toggle between "NES Pad" or "Other Pad".

**Comment by Kitrinx** [comment]
The savestate key combination was designed to avoid accident triggering, so it requires intentional unconventional keypresses to achieve.  There's no circumstance in which start + directional should be difficult to press on NES, so it's your discretion where you choose to map the savestate button for your comfort.

Rather than trying to explain the pitfalls of having save and load state too easy to trigger, I am going to allow Rick & Morty to do the talking in this video excerpt:
https://www.youtube.com/watch?v=K8DaX0FFthc

**Comment by JoshClose** [comment]
Wow that was so good. I officially need to binge Rick & Morty.

**Comment by klaritan** [comment]
I like that it was designed accidental presses in mind, but I wish you could customize it so if the user wishes to risk it they can change it to be more convenient, for save and load each.
