### ISSUE TITLE
Incorrect color emphasis behavior when two bits are set

### ISSUE THREAD

**Issue by BMF54123** [MiSTer-devel/NES_MiSTer#263]
In the MiSTer NES core, enabling two color emphasis bits simultaneously causes all three channels to be darkened. As a result, you cannot get yellow, magenta, or cyan tints.

MiSTer core:
![image](https://user-images.githubusercontent.com/15024035/130404318-d47fa665-1ed8-4513-9f5c-da8b7014e2ed.png)

AV Famicom (stock composite output):
![image](https://user-images.githubusercontent.com/15024035/130404296-29ffddea-4233-4c33-bb95-eb7e334b4e2f.png)

This behavior occurs regardless of which palette is selected in the menu.

**Comment by birdybro** [comment]
Do you have a link to this test rom?

**Comment by BMF54123** [comment]
[full_palette.zip](https://github.com/MiSTer-devel/NES_MiSTer/files/7132982/full_palette.zip)

**Comment by birdybro** [comment]
This should be fixed in the latest unstable build.

https://github.com/MiSTer-unstable-nightlies/NES_MiSTer/releases/download/unstable-builds/NES_unstable_20210906_f36f.rbf

**Comment by BMF54123** [comment]
Well, there's _some_ color now, but it is really faint compared with the real Famicom capture above. Tested both the unstable build and the latest build from 9/10/21:

![image](https://user-images.githubusercontent.com/15024035/132967206-6b50513c-9748-40a7-a70f-dafcbb591f53.png)

**Comment by sorgelig** [comment]
this is my version:
[NES.zip](https://github.com/MiSTer-devel/NES_MiSTer/files/7149446/NES.zip)

it has slightly different tints on some enphasis, but at least it gives different tints in all groups.
Currently core operates in rgb pixel level for tint while it should:
1) use original phase coded color.
2) use YIQ color space.
Each emphasis bit uses 1/3 of whole phase range and thus it doesn't affect cleanly R, G or B. So enphasis has "dirty" tint. That's why real NES has dirty green in "011" tint mode while my version (using RGB color space on pixels level) produces logically Yellow tint.
Probably, instead of making tint over-complicated, we can hardcode tint substraction table. it won't be 100% correct but will be hard to distinguish.

**Comment by sorgelig** [comment]
this build has some adjustments:
[NES_adj.zip](https://github.com/MiSTer-devel/NES_MiSTer/files/7149584/NES_adj.zip)

**Comment by BMF54123** [comment]
That is definitely a huge improvement! However, it appears that the entire image is now shifted right by one pixel (e.g. the right-most pixel on the screen is missing, and there is an extra black pixel at the left edge). Cropping and resolution settings don't seem to affect it.

**Comment by sorgelig** [comment]
That's easy to correct.
I will proceed with new emphasis.

**Comment by Kitrinx** [comment]
is this resolved? There's only a handful of games that use emphasis at all, mostly for just dimming the screen.
