### ISSUE TITLE
Extra Sprites?

### ISSUE THREAD

**Issue by RetroDriven** [MiSTer-devel/NES_MiSTer#5]
Would it be possible to add an extra sprites support option similar to the PCE Core to help with some games that have bad blinking?

**Comment by sorgelig** [comment]
I don't know yet. Even in PCE some games doing tricks to force flicker the sprites by alternating them between objects, so increasing the limit doesn't stop flickering in such games.

What games i need to test for this issue?

**Comment by sorgelig** [comment]
Hmm. I've messed the cores. I've though it's about Genesis core.
I didn't work on NES core yet, so i have no idea if it's possible in current implementation.

**Comment by Jeebs14** [comment]
I wanted to revisit this to see if this was still do able on the NES Core. A good example of games that flicker is Castelvania.

**Comment by sirblew** [comment]
I'd love to see this implemented too. Sprite flicker is really bad on a number of NES games and emulators such as Nestopia have a No Sprite Limit feature: https://fantasyanime.com/emuhelp/nestopia#no-sprite-limit

**Comment by saftle** [comment]
I opened a bounty for this issue starting at $30 here!:
https://www.bountysource.com/issues/65006463-extra-sprites.

---------
Please add to the pot, if you'd like to see whoever implement this get at least a little something for their hard work! :D

**Comment by sorgelig** [comment]
FPGA is not a software emulator. In software emulator it's always possible to insert as much actions as possible into a single machine step because modern CPU hundred thousands times faster than emulated one. 
In FPGA, close replica does the same as original HW did. So in most cases it's impossible to process more sprites than original HW does. In rare cases it's possible to improve it, but it's mostly exceptional cases than general.

**Comment by hmusta** [comment]
This feature is implemented in both the AVS and the Analogue NT mini, so it's technically possible. Someone just has to put in the effort.

**Comment by sirblew** [comment]
> This feature is implemented in both the AVS and the Analogue NT mini, so it's technically possible. Someone just has to put in the effort.

It's also a feature on the PC Engine core on MiSTer

**Comment by sorgelig** [comment]
What's relation of PC Engine to NES? (facepalm)

**Comment by saftle** [comment]
I removed the bounty at the request of Rysha, since she said she was working on this currently and does not want the bounty.

**Comment by Kitrinx** [comment]
This is now resolved.

**Comment by Dwedit** [comment]
I think it could be improved by some simple Mask Detection logic:

*    Look at the first 17 sprites
*    When looking at sprites, disregard their X coordinate, but see if they have the same tile number, Y coordinate, and Attributes.
*    Iterate through the 17 sprites.
*    There are three sprites you want to try to match: Sprite 0, The first sprite that didn't match sprite 0, and The second sprite that didn't match either.
*    Count the number of matches.
*    If there are 8 matches of sprite 0, mask away those scanlines (prevent drawing sprites for the entire 8 or 16 scanlines)
*    If there are 8 matches of First Distinct Sprite, mask away those scanlines
*    If there are 8 matches of Second Distinct Sprite, mask away those scanlines

**Comment by Kitrinx** [comment]
So if I understand you correctly, you're saying to look for 8 copies of the same sprite and interpret that as an intentional action from the developers to cause sprite clipping, and as such disregard extra sprites for this this line? I assume this is for games like Zelda and Castlevania II that are known to use sprite overflow for effect.

**Comment by Dwedit** [comment]
Some example games:

* Legend of Zelda (Top and Bottom doors)
* Castlevania II (Swamps)
* Gremlins 2 (in Cutscenes)
* Gimmick! (for the effect where the player jumps out of the doorway)

All those games will intentionally place 8 consecutive identical sprites (Gremlins 2 does not use the same X coordinate for some reason) for a masking effect to prevent other sprites from being drawn.  So if you see 8 sprites with the same Y coordinate, attribute byte, and tile number, then it's intentional masking and the game doesn't want to draw any more sprites in those scanlines.

For making an emulator, the first approach (looking at the first 17 sprites) will work, but for making low level emulators or hardware, stopping sprite evaluation early would be better.

**Comment by Kitrinx** [comment]
In hardware there aren't enough cycles to linearly evaluate more than 8 sprites (there are just enough cycles to traverse the 64 sprite OAM and copy 8 sprites if found) while also maintaining accurate behavior, so I do the extra 8 sprites simultaneously to the first 8, but I can simply set a register at the end of sprite evaluation that prevents the sprite fetches from taking place for the extra sprites and marks them as dummy sprites instead.

**Comment by Kitrinx** [comment]
I have implemented your suggestion, thank you.

**Comment by RetroDriven** [comment]
Extra Sprites feature has been added - Thank you so much =)
