### ISSUE TITLE
Galaxian (Japan) (Rev A) does not start

### ISSUE THREAD

**Issue by stefanerwinmayer** [MiSTer-devel/NES_MiSTer#71]
This seems to be one of the trickier games to emulate:
https://wiki.nesdev.com/w/index.php/Tricky-to-emulate_games

Trying to launch it only shows a blank background, often in the colour of the previously loaded game's background:
e. g. light blue if loaded after Super Mario Bros., black if loaded after Galaga

**Comment by cr4zymanz0r** [comment]
Core 20190428
Tested and get the same issue (black screen) on Rev A, but when I try the regular non-Rev A rom then I get the same behavior but the green LED on the IO board blink continually.

**Comment by greyrogue** [comment]
This is caused by the size of the ROM.  Galaxian (Japan) is the only 8KB PRG ROM, and NES 1.0 only supports 16KB size blocks.  The game can be played now by copying/pasting the PRG ROM to fill 16KB.  Long term, NES 2.0 now supports oddly sized ROMs (including Galaixan) with an alternate header.  This functionality needs to be added to the core before this will work, though.

**Comment by paulb-nl** [comment]
This should be closed because Rev A is an invalid rom. Other versions with the correct size work.

**Comment by sorgelig** [comment]
Ok, closed.
Can be re-opened if it will be required.
